Description of add_history
add_history
PURPOSE
Adds HIST_STR to OBJNAME's history field.
SYNOPSIS
function [subj] = add_history(subj,objtype,objname,hist_str,displayme)
DESCRIPTION
 Adds HIST_STR to OBJNAME's history field.
 [SUBJ] = ADD_HISTORY(SUBJ,HIST_STR,OBJTYPE,OBJNAME,[DISPLAYME])
 DISPLAYME (optional, default = false). If true, the HIST_STR gets
 echoed to the screen as well.
 If OBJTYPE = 'subj', then will append to the SUBJ header.history
CROSS-REFERENCE INFORMATION
This function calls:
datetime Spits out the date and time in yymmdd_HHMM format
get_object Return the entire object.
set_object Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
This function is called by:
create_pattern_from_mask Creates a new pattern by masking an old one
create_thresh_mask Create a boolean mask by thresholding a statmap
create_xvalid_indices Creates a selector for each iteration for leave-one-out cross-validation.
load_afni_mask Loads an AFNI dataset into the subj structure as a mask
load_afni_pattern Loads an AFNI dataset into a subject structure
load_pattern_from_hd Reverse of MOVE_PATTERN_TO_HD
move_pattern_to_hd Moves the pattern MAT to the hard disk
save_subj This just saves the subj structure to a file.
scramble_regressors Scrambles your regressors for sanity-checking
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
zscore_runs Zscore each voxel, separately for each run
SUBFUNCTIONS
function [subj] = add_subj_history(subj,hist_str)
SOURCE CODE
function [subj] = add_history(subj,objtype,objname,hist_str,displayme)
% Adds HIST_STR to OBJNAME's history field.
%
% [SUBJ] = ADD_HISTORY(SUBJ,HIST_STR,OBJTYPE,OBJNAME,[DISPLAYME])
%
% DISPLAYME (optional, default = false). If true, the HIST_STR gets
% echoed to the screen as well.
%
% If OBJTYPE = 'subj', then will append to the SUBJ header.history
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if ~exist('displayme')
  displayme = false;
end
if displayme
  disp(hist_str);
end
hist_str = sprintf('%s: %s',datetime(),hist_str);
% Deal with OBJTYPE == 'subj' as a special case
if strcmp(objtype,'subj')
  subj = add_subj_history(subj,hist_str);
  return
end
obj = get_object(subj,objtype,objname);
if ~isfield(obj,'header')
  obj.header.history = [];
end
if ~isfield(obj.header,'history')
  obj.header.history=[];
end
obj.header.history{end+1}=hist_str;
subj = set_object(subj,objtype,objname,obj);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [subj] = add_subj_history(subj,hist_str)
% [SUBJ] = ADD_SUBJ_HISTORY(SUBJ,HIST_STR)
%
% Appends the hist_str to the subj.header
if ~isfield(subj,'header')
  subj.header.history=[];
end
if ~isfield(subj.header,'history')
  subj.header.history=[];
end
subj.header.history{end+1}=hist_str;