Description of add_created
add_created
PURPOSE
Makes it easier to add the object-creation data easier
SYNOPSIS
function [subj] = add_created(subj,objtype,objname,new_creat)
DESCRIPTION
 Makes it easier to add the object-creation data easier
 [SUBJ] = ADD_CREATED(SUBJ,OBJTYPE,OBJNAME,NEW_CREAT)
 Basically, you can feed it an entire NEW_CREAT structure, and
 it will add any fields that didn't already exist, overwrite any
 that did, but leave intact those that were already there.
CROSS-REFERENCE INFORMATION
This function calls:
add_struct_fields Auxiliary function
get_objfield Retrieves a field from an object
set_objfield Replace or add a field to an object
This function is called by:
create_pattern_from_mask Creates a new pattern by masking an old one
create_thresh_mask Create a boolean mask by thresholding a statmap
create_xvalid_indices Creates a selector for each iteration for leave-one-out cross-validation.
load_afni_mask Loads an AFNI dataset into the subj structure as a mask
load_afni_pattern Loads an AFNI dataset into a subject structure
scramble_regressors Scrambles your regressors for sanity-checking
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
zscore_runs Zscore each voxel, separately for each run
SOURCE CODE
function [subj] = add_created(subj,objtype,objname,new_creat)
% Makes it easier to add the object-creation data easier
%
% [SUBJ] = ADD_CREATED(SUBJ,OBJTYPE,OBJNAME,NEW_CREAT)
%
% Basically, you can feed it an entire NEW_CREAT structure, and
% it will add any fields that didn't already exist, overwrite any
% that did, but leave intact those that were already there.
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if nargin < 4
  error('I think you missed out an argument');
end
old_creat = get_objfield(subj,objtype,objname,'created');
both_creat = add_struct_fields(new_creat,old_creat);
subj = set_objfield(subj,objtype,objname,'created',both_creat,'ignore_created',true);