Description of exist_objfield
exist_objfield
PURPOSE
Checks whether the field exists
SYNOPSIS
function [isthere] = exist_objfield(subj,objtype,objname,fieldname)
DESCRIPTION
 Checks whether the field exists
 [ISTHERE] = EXIST_FIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME)
 Checks whether the FIELDNAME exists inside the object OBJNAME of
 OBJTYPE.
 Returns true if it does, else false.
CROSS-REFERENCE INFORMATION
This function calls:
get_object Return the entire object.
This function is called by:
duplicate_object Duplicate an object
get_mat Returns the MAT field of the object
load_pattern_from_hd Reverse of MOVE_PATTERN_TO_HD
move_pattern_to_hd Moves the pattern MAT to the hard disk
remove_objfield Removes a field from the object
set_mat Updates the MAT contents of an object
set_objsubfield Sets the subfield of the object to NEWVAL.
summarize Prints info about the contents of the subj structure
SOURCE CODE
function [isthere] = exist_objfield(subj,objtype,objname,fieldname)
% Checks whether the field exists
%
% [ISTHERE] = EXIST_FIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME)
%
% Checks whether the FIELDNAME exists inside the object OBJNAME of
% OBJTYPE.
%
% Returns true if it does, else false.
obj = get_object(subj,objtype,objname);
if isfield(obj,fieldname)
  isthere = true;
else
  isthere = false;
end