Description of find_group
find_group
PURPOSE
Returns a list of names of objects from this group
SYNOPSIS
function [matches] = find_group(subj,objtype,groupname)
DESCRIPTION
 Returns a list of names of objects from this group
 [MATCHES] = FIND_GROUP(SUBJ,OBJTYPE,GROUPNAME)
 Returns a cell array of the names of all objects within SUBJ of
 OBJTYPE object type that belong to group GROUPNAME
 Returns no names if groupname is empty
CROSS-REFERENCE INFORMATION
This function calls:
get_type For internal use. Returns the entire cell array of a given type
This function is called by:
change_groupname Changes the groupname for all objects in a group
create_thresh_mask Create a boolean mask by thresholding a statmap
cross_validation Cross-validation classification
feature_select No-peeking feature selection
remove_group Removes an entire group's worth of objects permanently
summarize Prints info about the contents of the subj structure
write_to_afni Writes an object to a file, using the header info from a specified file.
SOURCE CODE
function [matches] = find_group(subj,objtype,groupname)
% Returns a list of names of objects from this group
%
% [MATCHES] = FIND_GROUP(SUBJ,OBJTYPE,GROUPNAME)
%
% Returns a cell array of the names of all objects within SUBJ of
% OBJTYPE object type that belong to group GROUPNAME
%
% Returns no names if groupname is empty
if nargin~=3
  error('I think you''ve forgotten to feed in all your arguments');
end
matches = {};
if isempty(groupname)
  return
end
objcell = get_type(subj,objtype);
nbr_objects = length(objcell);
for i=1:nbr_objects
  if strmatch(objcell{i}.group_name,groupname,'exact')
    matches{end+1} = objcell{i}.name;
  end
end