Description of get_object
get_object
PURPOSE
Return the entire object.
SYNOPSIS
function [obj] = get_object(subj,objtype,objname)
DESCRIPTION
 Return the entire object.
 [OBJ] = GET_OBJECT(SUBJ,OBJTYPE,OBJNAME)
 Can often be useful for peering inside a particular object. For
 instance, to view its innards of a pattern called 'epi_z', just
 type:
   get_object(subj,'pattern','epi_z')
 Technical note: You can also set OBJTYPE to 'subj', and return the
 subj structure itself back. This is useful for scripts that access
 the header
CROSS-REFERENCE INFORMATION
This function calls:
get_number Internal function - find the cell index of an object
get_type For internal use. Returns the entire cell array of a given type
This function is called by:
add_history Adds HIST_STR to OBJNAME's history field.
display_history Display the object's history field in a friendly way
duplicate_object Duplicate an object
exist_objfield Checks whether the field exists
exist_objsubfield Checks whether the subfield exists
get_objfield Retrieves a field from an object
remove_objfield Removes a field from the object
set_objfield Replace or add a field to an object
SOURCE CODE
function [obj] = get_object(subj,objtype,objname)
% Return the entire object.
%
% [OBJ] = GET_OBJECT(SUBJ,OBJTYPE,OBJNAME)
%
% Can often be useful for peering inside a particular object. For
% instance, to view its innards of a pattern called 'epi_z', just
% type:
%
%   get_object(subj,'pattern','epi_z')
%
% Technical note: You can also set OBJTYPE to 'subj', and return the
% subj structure itself back. This is useful for scripts that access
% the header
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if nargin~=3
  error('I think you''ve forgotten to feed in all your arguments');
end
if strcmp(objtype,'subj')
  obj = subj;
  return
end
objcell = get_type(subj,objtype);
objno = get_number(subj,objtype,objname);
obj = objcell{objno};