Description of get_objsubfield
get_objsubfield
PURPOSE
Returns the subfield for this object
SYNOPSIS
function [val] = get_objsubfield(subj,objtype,objname,fieldname,subfieldname)
DESCRIPTION
 Returns the subfield for this object
 [VAL] = GET_SUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME)
 For instance, if you wanted to know which function created a
 particular object:
   function_used = get_objsubfield(subj,'pattern','epi_z','creation','function');
CROSS-REFERENCE INFORMATION
This function calls:
get_objfield Retrieves a field from an object
This function is called by:
load_pattern_from_hd Reverse of MOVE_PATTERN_TO_HD
move_pattern_to_hd Moves the pattern MAT to the hard disk
save_subj This just saves the subj structure to a file.
summarize Prints info about the contents of the subj structure
SOURCE CODE
function [val] = get_objsubfield(subj,objtype,objname,fieldname,subfieldname)
% Returns the subfield for this object
%
% [VAL] = GET_SUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME)
%
% For instance, if you wanted to know which function created a
% particular object:
%
%   function_used = get_objsubfield(subj,'pattern','epi_z','creation','function');
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if nargin~=5
  error('I think you''ve forgotten to feed in all your arguments');
end
field = get_objfield(subj,objtype,objname,fieldname);
if ~isfield(field,subfieldname)
  error( sprintf('No subfield %s exists in %s field of %s %s', ...
       subfieldname,fieldname,objname,objtype) );
end
val = field.(subfieldname);