Description of get_type
get_type
PURPOSE
For internal use. Returns the entire cell array of a given type
SYNOPSIS
function [objcell] = get_type(subj,objtype)
DESCRIPTION
 For internal use. Returns the entire cell array of a given type
 [OBJCELL] = GET_TYPE(SUBJ,OBJTYPE)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
find_group Returns a list of names of objects from this group
get_mat Returns the MAT field of the object
get_name Internal function - gets the object's name from its cell index
get_number Internal function - find the cell index of an object
get_object Return the entire object.
init_object Add a new empty object
remove_object This removes an object permanently
set_mat Updates the MAT contents of an object
set_object Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
summarize Prints info about the contents of the subj structure
SOURCE CODE
function [objcell] = get_type(subj,objtype)
% For internal use. Returns the entire cell array of a given type
%
% [OBJCELL] = GET_TYPE(SUBJ,OBJTYPE)
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
% Check to see whether the type has been inputted as upper-case
if isempty(strmatch(lower(objtype),objtype,'exact'))
  error('Use lower-case to refer to the objtype');
end
switch(objtype)
 case 'pattern'
  objcell = subj.patterns;
 case 'regressors'
  objcell = subj.regressors;
 case 'selector'
  objcell = subj.selectors;
 case 'mask'
  objcell = subj.masks;
 case 'subj'
  error('You''ve tried to get an objtype called ''subj'' - doesn''t make sense');
 otherwise
  error('Unknown object type');
end
if ~iscell(objcell) & ~isempty(objcell)
  error( sprintf('Unrecoverable error with your entire %s set - should be a cell array',objtype) );
end