Description of get_masked_pattern
get_masked_pattern
PURPOSE
Returns the pattern's voxels allowed by the mask
SYNOPSIS
function [masked_pat ia ib] = get_masked_pattern(subj,patname,maskname)
DESCRIPTION
 Returns the pattern's voxels allowed by the mask
 [MASKED_PAT IA IB] = GET_MASKED_PATTERN(SUBJ,PATNAME,MASKNAME)
 Calls get_pattern to retrieve the PATNAME mat, and then applies the
 boolean MASKNAME volume to whittle down the voxels, and returns this
 smaller patterns mat. See the section, 'Figuring out which voxel
 is which, and where' in the manual for more information.
 Note: this returns a pattern matrix (included_voxels x
 timepoints). It's up to the user to init this as a proper object
 if so desired
 Will not warn you if no voxels are allowed through. Up to the
 user to check for this
CROSS-REFERENCE INFORMATION
This function calls:
compare_size Returns true if two matrices are the same size
get_mat Returns the MAT field of the object
get_ref_vol Returns the mat of the pattern's masked_by mask
This function is called by:
create_pattern_from_mask Creates a new pattern by masking an old one
cross_validation Cross-validation classification
SOURCE CODE
function [masked_pat ia ib] = get_masked_pattern(subj,patname,maskname)
% Returns the pattern's voxels allowed by the mask
%
% [MASKED_PAT IA IB] = GET_MASKED_PATTERN(SUBJ,PATNAME,MASKNAME)
%
% Calls get_pattern to retrieve the PATNAME mat, and then applies the
% boolean MASKNAME volume to whittle down the voxels, and returns this
% smaller patterns mat. See the section, 'Figuring out which voxel
% is which, and where' in the manual for more information.
%
% Note: this returns a pattern matrix (included_voxels x
% timepoints). It's up to the user to init this as a proper object
% if so desired
%
% Will not warn you if no voxels are allowed through. Up to the
% user to check for this
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
pat = get_mat(subj,'pattern',patname);
% Get the reference space volumes of the new mask and the pattern's
% own mask. They should be the same dimensions
childvol = get_mat(subj,'mask',maskname);
parentvol = get_ref_vol(subj,patname);
% xxx Allow for 2D masks???
if ndims(parentvol) ~= 3
  error('Your parent vol isn''t 3 dimensions');
end
if ~compare_size(childvol,parentvol)
  error('Your parent and child mask volumes are different sizes');
end
% both these sets of indices are now relative to the reference volume
% space
childidx = find(childvol);
parentidx = find(parentvol);
[intersectidx ia ib] = intersect(parentidx,childidx);
idx_of_child_items_contained_in_parent = ia;
if length(intersectidx) ~= length(childidx)
  warning('Some voxels present in the mask were not present in the pattern');
end
masked_pat = pat(idx_of_child_items_contained_in_parent,:);