Description of get_typeslist
get_typeslist
PURPOSE
Auxiliary function
SYNOPSIS
function [types] = get_typeslist(plurality)
DESCRIPTION
 Auxiliary function
 [TYPES] = GET_TYPESLIST(PLURALITY)
 Returns a cell array of strings
 with the names of the main types
 Set PLURALITY to 'single' or 'plural'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_number Internal function - find the cell index of an object
init_object Add a new empty object
remove_objfield Removes a field from the object
summarize Prints info about the contents of the subj structure
SOURCE CODE
function [types] = get_typeslist(plurality)
% Auxiliary function
%
% [TYPES] = GET_TYPESLIST(PLURALITY)
%
% Returns a cell array of strings
% with the names of the main types
%
%
% Set PLURALITY to 'single' or 'plural'
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
switch(plurality)
 case 'single'
  types{1} = 'pattern';
  types{2} = 'regressors';
  types{3} = 'selector';
  types{4} = 'mask';
 case 'plural'
  types{1} = 'patterns';
  types{2} = 'regressors';
  types{3} = 'selectors';
  types{4} = 'masks';
 otherwise
  error('Unknown plurality type');
end