Description of init_subj
init_subj
PURPOSE
Returns an empty initialized SUBJ structure
SYNOPSIS
function [subj] = init_subj(exp_name,id,varargin)
DESCRIPTION
 Returns an empty initialized SUBJ structure
 [SUBJ] = INIT_SUBJ(EXP_NAME,ID,...)
 The empty SUBJ structure contains no patterns, regressors, selectors
 masks. Adds some rudimentary header info, including the following
 string arguments
 EXP_NAME: The name of the experiment
 ID: a unique identifier for the subj, e.g. id/name/initials
 SUBDIR: (optional, default is exp_name id datetime) The
 subdirectory for storing auxiliary files
 USERNAME (optional, default = ''): The user's name
 e.g. subj = init_subj('my_experiment','GJD')
      subj = init_subj('my_experiment','GJD','mydatadir','greg');
CROSS-REFERENCE INFORMATION
This function calls:
datetime Spits out the date and time in yymmdd_HHMM format
propval This deals with property/value pairs of optional arguments.
set_objfield Replace or add a field to an object
This function is called by:
tutorial_easy Tutorial script to accompany TUTORIAL_EASY.HTM
SOURCE CODE
function [subj] = init_subj(exp_name,id,varargin)
% Returns an empty initialized SUBJ structure
%
% [SUBJ] = INIT_SUBJ(EXP_NAME,ID,...)
%
% The empty SUBJ structure contains no patterns, regressors, selectors
% masks. Adds some rudimentary header info, including the following
% string arguments
%
% EXP_NAME: The name of the experiment
%
% ID: a unique identifier for the subj, e.g. id/name/initials
%
% SUBDIR: (optional, default is exp_name id datetime) The
% subdirectory for storing auxiliary files
%
% USERNAME (optional, default = ''): The user's name
%
% e.g. subj = init_subj('my_experiment','GJD')
%      subj = init_subj('my_experiment','GJD','mydatadir','greg');
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
version = 3;
created = datetime(true);
defaults.subdir = sprintf('%s_%s_%s',exp_name,id,created);
defaults.username = '';
args = propval(varargin,defaults);
% Initializes a new subject structure
subj.patterns   = {};
subj.regressors = {};
subj.selectors  = {};
subj.masks      = {};
subj.header     = [];
header.experiment = exp_name;
header.version    = version;
header.history    = {sprintf('Initialized on %s',created)};
header.created    = created;
header.subdir     = args.subdir;
header.username   = args.username;
header.id         = id;
subj = set_objfield(subj,'subj','','header',header);
subj.p  = 'Unspecified';
subj.s  = 'Unspecified';
subj.m  = 'Unspecified';
subj.r  = 'Unspecified';