Description of remove_objsubfield
remove_objsubfield
PURPOSE
Removes the subfield from an object.
SYNOPSIS
function [subj] = remove_objsubfield(subj,objtype,objname,fieldname,subfieldname,newval)
DESCRIPTION
 Removes the subfield from an object.
 SUBJ = REMOVE_SUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME,NEWVAL)
 See remove_objsubfield for more information
CROSS-REFERENCE INFORMATION
This function calls:
get_objfield Retrieves a field from an object
set_objfield Replace or add a field to an object
This function is called by:
load_pattern_from_hd Reverse of MOVE_PATTERN_TO_HD
SOURCE CODE
function [subj] = remove_objsubfield(subj,objtype,objname,fieldname,subfieldname,newval)
% Removes the subfield from an object.
%
% SUBJ = REMOVE_SUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME,NEWVAL)
%
% See remove_objsubfield for more information
if ~nargout
  error('Don''t forget to catch the subj structure that gets returned');
end
field = get_objfield(subj,objtype,objname,fieldname);
field = rmfield(field,subfieldname);
subj = set_objfield(subj,objtype,objname,fieldname,field);