Description of save_subj
save_subj
PURPOSE
This just saves the subj structure to a file.
SYNOPSIS
function [subj fn] = save_subj(subj,varargin)
DESCRIPTION
 This just saves the subj structure to a file.
 [SUBJ FN] = SAVE_SUBJ(SUBJ,...)
 It's useful because it does lots of book-keeping, and won't
 overwrite existing files unless you tell it to
 FN = the filename it saved itself under. This is useful in cases
 where it had to choose a new one because the default/user-provided
 one was already taken
 CREATE_LOG (optional, default = true) creates a textfile
 filename_subjID_datetime.log with the current summarize and header
 info for easy reference without having to load in the mat
 SAVE_INFO (optional, default = []). This is a string that gets
 displayed and appended to the subj.header.history. Useful if you
 want to put a comment about why you're saving this subject or what
 state things are in - this gets displayed in the terminal and
 appended to the header history. if you don't feed in a save_info, or
 an empty one, then it will automatically create a simple one
 containing time and filename
 PATHFILESTEM (optional, default = 'subj')
 APPEND_DATE (optional, default = true) - appends the date to the
 pathfilestem
 OVERWRITE_IF_EXIST (optional, default = false). If true, will
 overwrite files with the same name if they exist
 e.g. [subj filename] = save_subj(subj);
 e.g. subj = save_subj(subj,'pathfilestem','~/blah/my_subj', ...
                            'append_date',true, ...
                            'save_info','Great classification');
 If you want to add something besides the subj to the file as well then
 append it afterwards, e.g. to append the results structure to the
 file this function creates, call this next:
   save(filename,'-append','results');
 xxx ID and SUBDIR functionality not finished yet
CROSS-REFERENCE INFORMATION
This function calls:
add_history Adds HIST_STR to OBJNAME's history field.
datetime Spits out the date and time in yymmdd_HHMM format
get_objsubfield Returns the subfield for this object
propval This deals with property/value pairs of optional arguments.
set_objsubfield Sets the subfield of the object to NEWVAL.
This function is called by:
SOURCE CODE
function [subj fn] = save_subj(subj,varargin)
% This just saves the subj structure to a file.
%
% [SUBJ FN] = SAVE_SUBJ(SUBJ,...)
%
% It's useful because it does lots of book-keeping, and won't
% overwrite existing files unless you tell it to
%
% FN = the filename it saved itself under. This is useful in cases
% where it had to choose a new one because the default/user-provided
% one was already taken
%
% CREATE_LOG (optional, default = true) creates a textfile
% filename_subjID_datetime.log with the current summarize and header
% info for easy reference without having to load in the mat
%
% SAVE_INFO (optional, default = []). This is a string that gets
% displayed and appended to the subj.header.history. Useful if you
% want to put a comment about why you're saving this subject or what
% state things are in - this gets displayed in the terminal and
% appended to the header history. if you don't feed in a save_info, or
% an empty one, then it will automatically create a simple one
% containing time and filename
%
% PATHFILESTEM (optional, default = 'subj')
%
% APPEND_DATE (optional, default = true) - appends the date to the
% pathfilestem
%
% OVERWRITE_IF_EXIST (optional, default = false). If true, will
% overwrite files with the same name if they exist
%
% e.g. [subj filename] = save_subj(subj);
%
% e.g. subj = save_subj(subj,'pathfilestem','~/blah/my_subj', ...
%                            'append_date',true, ...
%                            'save_info','Great classification');
%
% If you want to add something besides the subj to the file as well then
% append it afterwards, e.g. to append the results structure to the
% file this function creates, call this next:
%   save(filename,'-append','results');
%
% xxx ID and SUBDIR functionality not finished yet
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
id = get_objsubfield(subj,'subj','','header','id');
subdir = get_objsubfield(subj,'subj','','header','subdir');
defaults.create_log = true;
defaults.save_info = [];
defaults.pathfilestem = 'subj';
defaults.append_date = true;
defaults.overwrite_if_exist = false;
args = propval(varargin,defaults);
dt = datetime();
% For brevity
fn = args.pathfilestem;
% Optionally append the date
if args.append_date
  fn = sprintf('%s_%s',fn,dt);
end
% If we're not prepared to overwrite existing files, then we have
% to keep appending a number to the end of the filename until we
% find a vacant spot
if ~args.overwrite_if_exist
  try_fn = fn;
  i = 1;
  % Keep incrementing as long as FN_i exists
  while exist( sprintf('%s.mat',try_fn),'file' )
    i = i+1;
    try_fn = sprintf('%s_%i',fn,i);
    disp( sprintf('filename %s already exists - trying %s',fn,try_fn) );
  end
  % If fn already existed, use try_fn instead
  if strcmp(fn,try_fn) ~= true
    fn = try_fn;
  end
end % if args.overwrite_if_exist
% Generate a default save_info, and add it to the subj history
if isempty(args.save_info)
  args.save_info = sprintf('Saving %s in %s at %s',fn,pwd,dt);
end
subj = add_history(subj,'subj','',args.save_info,true);
save(fn,'subj');
history = char(get_objsubfield(subj,'subj','','header','history'));
% Record in the subj that it's been saved
subj = set_objsubfield(subj,'subj','','header','last_saved',dt,'ignore_absence',true);
subj = set_objsubfield(subj,'subj','','header','last_saved_filename',fn,'ignore_absence',true);
% Optionally record the saveinfo to fn.log
if args.create_log
  out = fopen(sprintf('%s.log',fn),'w');
  nHists = size(history,1);
  for i=1:nHists
    fprintf(out, sprintf('%s\n',history(i,:)) );
  end % nHists
  fclose(out);
end