Description of set_objfield
set_objfield
PURPOSE
Replace or add a field to an object
SYNOPSIS
function [subj] = set_objfield(subj,objtype,objname,fieldname,newval,varargin)
DESCRIPTION
 Replace or add a field to an object
 [SUBJ] = SET_OBJFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,NEWVAL,...)
 Replaces/adds the FIELDNAME field in OBJNAME object of type OBJTYPE
 with NEWVAL. Will create the field if it doesn't exist, but will
 warn you unless you set IGNORE_ABSENCE = true
 IGNORE_ABSENCE (optional, default = false). By default, this will
 warn you if the field you're about to set doesn't already
 exist. Set to true if you're sure that's ok
 IGNORE_EMPTY (optional, default = false). By default, this will
 warn you if the field you're about to set is empty (and is
 overwriting a full one). Set to true if you're sure you want to
 do that
 IGNORE_CREATED (optional, default = false). By default, this will
 error if you try and set the 'created' field, but if this is
 true, then it continues as normal.
CROSS-REFERENCE INFORMATION
This function calls:
get_object Return the entire object.
propval This deals with property/value pairs of optional arguments.
set_object Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
This function is called by:
add_created Makes it easier to add the object-creation data easier
change_groupname Changes the groupname for all objects in a group
create_pattern_from_mask Creates a new pattern by masking an old one
create_thresh_mask Create a boolean mask by thresholding a statmap
create_xvalid_indices Creates a selector for each iteration for leave-one-out cross-validation.
duplicate_object Duplicate an object
feature_select No-peeking feature selection
init_subj Returns an empty initialized SUBJ structure
load_afni_pattern Loads an AFNI dataset into a subject structure
move_pattern_to_hd Moves the pattern MAT to the hard disk
remove_objsubfield Removes the subfield from an object.
set_mat Updates the MAT contents of an object
set_objsubfield Sets the subfield of the object to NEWVAL.
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
tutorial_easy Tutorial script to accompany TUTORIAL_EASY.HTM
SOURCE CODE
function [subj] = set_objfield(subj,objtype,objname,fieldname,newval,varargin)
% Replace or add a field to an object
%
% [SUBJ] = SET_OBJFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,NEWVAL,...)
%
% Replaces/adds the FIELDNAME field in OBJNAME object of type OBJTYPE
% with NEWVAL. Will create the field if it doesn't exist, but will
% warn you unless you set IGNORE_ABSENCE = true
%
% IGNORE_ABSENCE (optional, default = false). By default, this will
% warn you if the field you're about to set doesn't already
% exist. Set to true if you're sure that's ok
%
% IGNORE_EMPTY (optional, default = false). By default, this will
% warn you if the field you're about to set is empty (and is
% overwriting a full one). Set to true if you're sure you want to
% do that
%
% IGNORE_CREATED (optional, default = false). By default, this will
% error if you try and set the 'created' field, but if this is
% true, then it continues as normal.
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
% This looks long, but it's basically just:
%   get_object
%   obj.(fieldname) = newval
%   set_object
if ~nargout
  error('Don''t forget to catch the subj structure that gets returned');
end
defaults.ignore_absence = false;
defaults.ignore_empty = false;
defaults.ignore_created = false;
args = propval(varargin,defaults);
% If setting a field in the root of the SUBJ structure, deal with that
% separately here
if strcmp(objtype,'subj')
  if ~isfield(subj,fieldname) && ~args.ignore_absence
    warn_str = sprintf('No subj field called %s - creating it',fieldname);
    warning( warn_str );
    subj.(fieldname) = [];
  end
  subj.(fieldname) = newval;
  return
end
% Otherwise, get the object from the SUBJ structure
obj = get_object(subj,objtype,objname);
% Error-checking
switch(fieldname)
 case 'mat'
  error('You should use set_%s to retrieve the mat field',objtype);
 case 'history'
  error('You should use add_%s_history to add to the history',objtype);
 case 'created'
  if ~args.ignore_created
    error('You should use add_created to add information about the object''s creation');
  end
end
% If you're setting a field that doesn't exist, warn the user, to
% highlight possible typos
% But in case they're deliberately setting the field, check IGNORE_ABSENCE
if ~isfield(obj,fieldname) && ~args.ignore_absence
  warn_str = sprintf('No field in %s %s called %s - creating it', ...
           objname,objtype,fieldname);
  warning( warn_str );
  obj.(fieldname) = [];
end
if isempty(newval) && ~args.ignore_empty && ~isempty(obj.(fieldname))
  warning('About to overwrite a field with an empty one');
end
% Set the field in the object, and then set the object in the SUBJ
% structure
obj.(fieldname) = newval;
subj = set_object(subj,objtype,objname,obj);