Description of set_objsubfield
set_objsubfield
PURPOSE
Sets the subfield of the object to NEWVAL.
SYNOPSIS
function [subj] = set_objsubfield(subj,objtype,objname,fieldname,subfieldname,newval,varargin)
DESCRIPTION
 Sets the subfield of the object to NEWVAL.
 [SUBJ] = SET_OBJSUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME,NEWVAL,...)
 Works very similarly to SET_OBJFIELD.
 For instance, the DESCRIPTION of an object is stored in its
 HEADER.DESCRIPTION. To modify it:
    subj = set_objfield(subj,'pattern','raw','header','description', ...
                          'This contains my raw data');
 Use the optional IGNORE_ABSENCE and IGNORE_EMPTY flags like
 SET_OBJFIELD to avoid warnings
CROSS-REFERENCE INFORMATION
This function calls:
exist_objfield Checks whether the field exists
get_objfield Retrieves a field from an object
propval This deals with property/value pairs of optional arguments.
set_objfield Replace or add a field to an object
This function is called by:
load_afni_mask Loads an AFNI dataset into the subj structure as a mask
load_afni_pattern Loads an AFNI dataset into a subject structure
save_subj This just saves the subj structure to a file.
set_mat Updates the MAT contents of an object
SOURCE CODE
function [subj] = set_objsubfield(subj,objtype,objname,fieldname,subfieldname,newval,varargin)
% Sets the subfield of the object to NEWVAL.
%
% [SUBJ] = SET_OBJSUBFIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME,SUBFIELDNAME,NEWVAL,...)
%
% Works very similarly to SET_OBJFIELD.
%
% For instance, the DESCRIPTION of an object is stored in its
% HEADER.DESCRIPTION. To modify it:
%
%    subj = set_objfield(subj,'pattern','raw','header','description', ...
%                          'This contains my raw data');
%
% Use the optional IGNORE_ABSENCE and IGNORE_EMPTY flags like
% SET_OBJFIELD to avoid warnings
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if ~nargout
  error('Don''t forget to catch the subj structure that gets returned');
end
defaults.ignore_absence = false;
defaults.ignore_empty = false;
args = propval(varargin,defaults);
% Create the main field if it doesn't already exist
% This will deservedly trigger a warning in SET_FIELD
if ~exist_objfield(subj,objtype,objname,fieldname)
  subj = set_objfield(subj,objtype,objname,fieldname,[]);
end
field = get_objfield(subj,objtype,objname,fieldname);
% Warnings
if ~isfield(field,subfieldname) & ~args.ignore_absence
  warn_str = sprintf('No subfield %s in %s in %s %s - creating subfield', ...
           subfieldname,fieldname,objname,objtype);
  warning(warn_str);
  field.(subfieldname) = [];
end
if isempty(newval) & ~ignore_empty & ~isempty(field.(subfieldname))
  warning('About to overwrite a subfield with an empty one');
end
field.(subfieldname) = newval;
subj = set_objfield(subj,objtype,objname,fieldname,field);