Description of set_type
set_type
PURPOSE
Replace the entire cell array of this objtype with a new one
SYNOPSIS
function [subj] = set_type(subj,objtype,objcell)
DESCRIPTION
 Replace the entire cell array of this objtype with a new one
 [SUBJ] = SET_TYPE(SUBJ,OBJTYPE,OBJCELL)
 Recommended for internal use only
 See the discussion in the manual about memory efficiency for why
 this isn't an incredibly costly way to do things
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
init_object Add a new empty object
remove_object This removes an object permanently
set_mat Updates the MAT contents of an object
set_object Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
SOURCE CODE
function [subj] = set_type(subj,objtype,objcell)
% Replace the entire cell array of this objtype with a new one
%
% [SUBJ] = SET_TYPE(SUBJ,OBJTYPE,OBJCELL)
%
% Recommended for internal use only
%
% See the discussion in the manual about memory efficiency for why
% this isn't an incredibly costly way to do things
if ~nargout
  error('Don''t forget to catch the subj structure that gets returned');
end
if ~iscell(objcell)
  error('Trying to set %s cell array but it''s not a cell array');
end
switch(objtype)
 case 'pattern'
  subj.patterns = objcell;
 case 'regressors'
  subj.regressors = objcell;
 case 'selector'
  subj.selectors = objcell;
 case 'mask'
  subj.masks = objcell;
 otherwise
  error('Unknown object type');
end