Description of compare_size
compare_size
PURPOSE
Returns true if two matrices are the same size
SYNOPSIS
function [issame] = compare_size(m1,m2)
DESCRIPTION
 Returns true if two matrices are the same size
 [issame] = compare_size(m1,m2)
 Checks that M1 and M2 have the same number of dimensions and each
 dimension is the same size
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_masked_pattern Returns the pattern's voxels allowed by the mask
perfmet_maxclass This is the most basic performance metric.
perfmet_template This is the template perfmet function for creating your own
SOURCE CODE
function [issame] = compare_size(m1,m2)
% Returns true if two matrices are the same size
%
% [issame] = compare_size(m1,m2)
%
% Checks that M1 and M2 have the same number of dimensions and each
% dimension is the same size
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
issame = true;
if ndims(m1) ~= ndims(m2)
  issame = false;
  return
end
if ~all(size(m1)==size(m2))
  issame = false;
  return
end