Description of get_mat
get_mat
PURPOSE
Returns the MAT field of the object
SYNOPSIS
function [mat] = get_mat(subj,objtype,objname)
DESCRIPTION
 Returns the MAT field of the object
 [MAT] = GET_MAT(SUBJ,OBJTYPE,OBJNAME)
 The MAT field is where the goodies are stashed. For instance, it
 stores the data in a pattern, or the volume in a mask.
 If the object is being stored on the hard disk (see the manual
 section on 'Moving patterns' to the hard disk' for more info),
 then this will transparently retrieve the mat from there
CROSS-REFERENCE INFORMATION
This function calls:
exist_objfield Checks whether the field exists
get_number Internal function - find the cell index of an object
get_objfield Retrieves a field from an object
get_type For internal use. Returns the entire cell array of a given type
This function is called by:
create_thresh_mask Create a boolean mask by thresholding a statmap
create_xvalid_indices Creates a selector for each iteration for leave-one-out cross-validation.
cross_validation Cross-validation classification
duplicate_object Duplicate an object
feature_select No-peeking feature selection
get_masked_pattern Returns the pattern's voxels allowed by the mask
get_ref_vol Returns the mat of the pattern's masked_by mask
get_relative_index Returns an index into a mask of the voxels in a pattern xxx
load_afni_pattern Loads an AFNI dataset into a subject structure
load_pattern_from_hd Reverse of MOVE_PATTERN_TO_HD
move_pattern_to_hd Moves the pattern MAT to the hard disk
peek_feature_select Just like PEEK_FEATURE_SELECT, except that it peeks
scramble_regressors Scrambles your regressors for sanity-checking
shift_TRs
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
write_to_afni Writes an object to a file, using the header info from a specified file.
zscore_runs Zscore each voxel, separately for each run
SOURCE CODE
function [mat] = get_mat(subj,objtype,objname)
% Returns the MAT field of the object
%
% [MAT] = GET_MAT(SUBJ,OBJTYPE,OBJNAME)
%
% The MAT field is where the goodies are stashed. For instance, it
% stores the data in a pattern, or the volume in a mask.
%
% If the object is being stored on the hard disk (see the manual
% section on 'Moving patterns' to the hard disk' for more info),
% then this will transparently retrieve the mat from there
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
% Basically, all this does is:
%   objcell = get_type
%   objno = get_number
%   return objcell{objno}
if nargin~=3
  error('I think you''ve forgotten to feed in all your arguments');
end
mat = [];
% Uses the objno and objcell so that it's independent of object type
objno = get_number(subj,objtype,objname);
objcell = get_type(subj,objtype);
if ~exist_objfield(subj,objtype,objname,'mat')
  error( sprintf('The %s %s doesn''t have a .mat field',objname,objtype) );
end
% If the mat resides on the HD, load it in from there
if exist_objfield(subj,objtype,objname,'movehd')
  movehd = get_objfield(subj,objtype,objname,'movehd');
  disp( sprintf('Retrieving mat from %s',movehd.pathfilename) );
  load(movehd.pathfilename);
% Otherwise, just grab it from the objcell
else
  mat = objcell{objno}.mat;
end % isfield movehd
if isempty(mat)
  warning( sprintf('Retrieving an empty mat from %s',objname) );
end