Description of get_objfield
get_objfield
PURPOSE
Retrieves a field from an object
SYNOPSIS
function [val] = get_objfield(subj,objtype,objname,fieldname)
DESCRIPTION
 Retrieves a field from an object
 [VAL] = GET_FIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME)
   e.g. nvox = get_objfield(subj,'mask','wholebrain','nvox');
 Use OBJTYPE = 'subj' and OBJNAME = '' if you want to get a field
 in the root of the subj structure itself
   e.g. header = get_objfield(subj,'subj','','header');
CROSS-REFERENCE INFORMATION
This function calls:
get_object Return the entire object.
This function is called by:
add_created Makes it easier to add the object-creation data easier
create_thresh_mask Create a boolean mask by thresholding a statmap
duplicate_object Duplicate an object
get_mat Returns the MAT field of the object
get_objsubfield Returns the subfield for this object
get_ref_vol Returns the mat of the pattern's masked_by mask
get_relative_index Returns an index into a mask of the voxels in a pattern xxx
remove_objsubfield Removes the subfield from an object.
set_mat Updates the MAT contents of an object
set_objsubfield Sets the subfield of the object to NEWVAL.
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
summarize Prints info about the contents of the subj structure
write_to_afni Writes an object to a file, using the header info from a specified file.
SOURCE CODE
function [val] = get_objfield(subj,objtype,objname,fieldname)
% Retrieves a field from an object
%
% [VAL] = GET_FIELD(SUBJ,OBJTYPE,OBJNAME,FIELDNAME)
%
%   e.g. nvox = get_objfield(subj,'mask','wholebrain','nvox');
%
% Use OBJTYPE = 'subj' and OBJNAME = '' if you want to get a field
% in the root of the subj structure itself
%   e.g. header = get_objfield(subj,'subj','','header');
% This is part of the Princeton MVPA toolbox, released under the
% GPL. See http://www.csbmb.princeton.edu/mvpa for more
% information.
if nargin~=4
  error('I think you''ve forgotten to feed in all your arguments');
end
if strcmp(fieldname,'mat')
  error('You should use get_%s to retrieve the mat field',objtype);
end
if strcmp(objtype,'subj')
  obj = subj;
else
  obj = get_object(subj,objtype,objname);
end
if isfield(obj,fieldname)
  val = obj.(fieldname);
else
  error( sprintf('No %s fieldname in %s %s',fieldname,objname,objtype) );
end