Description of paint_vol
paint_vol
PURPOSE
Creates a new single-TR BRIK
SYNOPSIS
function [vol] = paint_vol(subj,objtype,objname,sample_brik_name,new_brik_name,varargin)
DESCRIPTION
 Creates a new single-TR BRIK
 [VOL] = PAINT_VOL(SUBJ,OBJTYPE,OBJNAME,SAMPLE_BRIK_NAME,NEW_BRIK_NAME,VARARGIN)
 This creates a new single-TR BRIK called NEW_BRIK_NAME.BRIK from the
 values in OBJNAME, which can be either a single-TR pattern or a
 mask.
 The SAMPLE_BRIK_NAME BRIK doesn't get written to at all, but we
 do steal its header. This is easier and probably safer than
 generating our own. However, it is important that the sample BRIK
 uses the same reference space as the mask and pattern xxx
 BRIKOPT (optional, default = []). If BRIKOPT.NoCheck is true, then
 EXPORT_TO_AFNI.M tells WRITEBRIK.M to skip all the extra
 checking. Not a good idea unless things won't work otherwise
 e.g. to visualise a statmap:
   vol = paint_vol(subj,'pattern','anova_statmap','samplebrik','newbrik');
CROSS-REFERENCE INFORMATION
This function calls:
export_to_afni Write an object out to an AFNI BRIK
get_mat Returns the MAT field of the object
propval This deals with property/value pairs of optional arguments.
This function is called by:
SOURCE CODE
function [vol] = paint_vol(subj,objtype,objname,sample_brik_name,new_brik_name,varargin)
% Creates a new single-TR BRIK
%
% [VOL] = PAINT_VOL(SUBJ,OBJTYPE,OBJNAME,SAMPLE_BRIK_NAME,NEW_BRIK_NAME,VARARGIN)
%
% This creates a new single-TR BRIK called NEW_BRIK_NAME.BRIK from the
% values in OBJNAME, which can be either a single-TR pattern or a
% mask.
%
% The SAMPLE_BRIK_NAME BRIK doesn't get written to at all, but we
% do steal its header. This is easier and probably safer than
% generating our own. However, it is important that the sample BRIK
% uses the same reference space as the mask and pattern xxx
%
% BRIKOPT (optional, default = []). If BRIKOPT.NoCheck is true, then
% EXPORT_TO_AFNI.M tells WRITEBRIK.M to skip all the extra
% checking. Not a good idea unless things won't work otherwise
%
% e.g. to visualise a statmap:
%
%   vol = paint_vol(subj,'pattern','anova_statmap','samplebrik','newbrik');
nVox = length(find(vol));
defaults.brikopt = []
args = propval(varargin,defaults);
mat = get_mat(subj,objtype,objname);
switch(objtype)
 case 'pattern'
  if size(mat,2)>1
    error('Can only deal with single TR patterns');
  end
 case 'mask'
 otherwise
  error('Must be a pattern or mask');
end
vol = convert_pattern_to_4d(subj,objname);
export_to_afni(vol,sample_brik_name,new_brik_name,brikopt);