subj = init_subj('','');

subj = create_anatomical_regions( ...
    subj, {}, ...
    '/jukebox/osherson/mattheww/BA_briks_tlrc/', ...
    '401_MPRAGE_r5_at+tlrc', ...
    '401_mask_d2+orig', ...
    'clean_up_briks', false);

subj = initset_object(subj,'mask','wholevol', ones(64,64,33) );
subj = load_afni_pattern(subj,'anat','wholevol', ...
                         '401_MPRAGE_r5_down+orig');
view_montage(subj,'pattern','anat','mask','BA10');
