Description of add_struct_fields
add_struct_fields
PURPOSE
Auxiliary function
SYNOPSIS
function [args] = add_struct_fields(specifieds,defaults)
DESCRIPTION
 Auxiliary function
 [ARGS] = ADD_STRUCT_FIELDS(SPECIFIEDS,DEFAULTS)
 Deals with user-specified arguments and default arguments as
 structs.
 It creates an amalgamated ARGS struct that assumes that if the user
 hasn't specified an argument in SPECIFIEDS, then it should use the
 one in DEFAULTS.
 It doesn't do as much error-checking as PROPVAL.M xxx
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
add_created Makes it easier to add the object-creation data easier
train_bp Creates a backpropagation neural network and trains it.
train_template Template for creating custom training functions
SOURCE CODE
function [args] = add_struct_fields(specifieds,defaults)
% Auxiliary function
%
% [ARGS] = ADD_STRUCT_FIELDS(SPECIFIEDS,DEFAULTS)
%
% Deals with user-specified arguments and default arguments as
% structs.
%
% It creates an amalgamated ARGS struct that assumes that if the user
% hasn't specified an argument in SPECIFIEDS, then it should use the
% one in DEFAULTS.
%
% It doesn't do as much error-checking as PROPVAL.M xxx
def_fnames = fieldnames(defaults);
args = specifieds;
for i=1:length(def_fnames)
  cur_def_fname = def_fnames{i};
  % If this default argument wasn't specified, then use the default
  % value
  if ~isfield(args,cur_def_fname)
    args.(cur_def_fname) = defaults.(cur_def_fname);
  end
end