Description of create_pattern_from_mask
create_pattern_from_mask
PURPOSE
Creates a new pattern by masking an old one
SYNOPSIS
function [subj] = create_pattern_from_mask(subj,old_patname,maskname,new_patname,varargin)
DESCRIPTION
 Creates a new pattern by masking an old one
 SUBJ = CREATE_PATTERN_FROM_MASK(SUBJ,OLD_PATNAME,MASKNAME,NEW_PATNAME,...)
 Creates a new pattern called NEW_PATNAME from an
 existing one called OLD_PATNAME, including only the voxels
 allowed through by MASKNAME
 Adds the following objects:
 - pattern (unless IGNORE_EMPTY condition)
 If the intersection is empty, it returns a warning and does not
 create a new patterns cell, unless IGNORE_EMPTY is true
 IGNORE_EMPTY (optional, default = false). By default, this exits
 without creating a pattern if no features are allowed through. If
 set to true, this will create the pattern anyway without issuing
 a warning
CROSS-REFERENCE INFORMATION
This function calls:
add_created Makes it easier to add the object-creation data easier
add_history Adds HIST_STR to OBJNAME's history field.
duplicate_object Duplicate an object
get_masked_pattern Returns the pattern's voxels allowed by the mask
propval This deals with property/value pairs of optional arguments.
set_mat Updates the MAT contents of an object
set_objfield Replace or add a field to an object
This function is called by:
SOURCE CODE
function [subj] = create_pattern_from_mask(subj,old_patname,maskname,new_patname,varargin)
% Creates a new pattern by masking an old one
%
% SUBJ = CREATE_PATTERN_FROM_MASK(SUBJ,OLD_PATNAME,MASKNAME,NEW_PATNAME,...)
%
% Creates a new pattern called NEW_PATNAME from an
% existing one called OLD_PATNAME, including only the voxels
% allowed through by MASKNAME
%
% Adds the following objects:
% - pattern (unless IGNORE_EMPTY condition)
%
% If the intersection is empty, it returns a warning and does not
% create a new patterns cell, unless IGNORE_EMPTY is true
%
% IGNORE_EMPTY (optional, default = false). By default, this exits
% without creating a pattern if no features are allowed through. If
% set to true, this will create the pattern anyway without issuing
% a warning
defaults.ignore_empty = false;
args = propval(varargin,defaults);
% Do the hard work
masked_pat = get_masked_pattern(subj,old_patname,maskname);
% Warn and return if no voxels are allowed through (unless IGNORE_EMPTY)
if isempty(masked_pat) & ~args.ignore_empty
  warn_str = sprintf('No features from %s were allowed through by %s - not creating %s', ...
           old_patname,maskname,new_patname);
  warning(warn_str);
  return
end
% Create the new object
subj = duplicate_object(subj,'pattern',old_patname,new_patname);
% Now replace the new pattern's mat with the masked_pat
subj = set_mat(subj,'pattern',new_patname,masked_pat,'ignore_diff_size',true);
subj = set_objfield(subj,'pattern',new_patname,'masked_by',maskname);
created.function = 'create_pattern_from_mask';
subj = add_created(subj,'pattern',new_patname,created);
hist = sprintf('Pattern ''%s'' created by %s',...
          new_patname,created.function);
subj = add_history(subj,'pattern',new_patname,hist,true);