Description of init_object
init_object
PURPOSE
Add a new empty object
SYNOPSIS
function [subj] = init_object(subj,objtype,new_objname);
DESCRIPTION
 Add a new empty object
 [SUBJ] = INIT_OBJECT(SUBJ,OBJTYPE,NEW_OBJNAME);
 Update the SUBJ structure by creating a new object of type OBJTYPE
 called NEW_OBJNAME
 Adds the following objects:
 - object
 This function will initialize everything to empty. If you want to
 base your new object on an existing one, use duplicate_object
 instead.
CROSS-REFERENCE INFORMATION
This function calls:
datetime Spits out the date and time in yymmdd_HHMM format
get_type For internal use. Returns the entire cell array of a given type
get_typeslist Auxiliary function
set_type Replace the entire cell array of this objtype with a new one
This function is called by:
duplicate_object Duplicate an object
load_afni_mask Loads an AFNI dataset into the subj structure as a mask
load_afni_pattern Loads an AFNI dataset into a subject structure
statmap_anova Use the anova to select features that vary between conditions
statmap_template This is the sample/template statmap generation function
tutorial_easy Tutorial script to accompany TUTORIAL_EASY.HTM
SOURCE CODE
function [subj] = init_object(subj,objtype,new_objname);
% Add a new empty object
%
% [SUBJ] = INIT_OBJECT(SUBJ,OBJTYPE,NEW_OBJNAME);
%
% Update the SUBJ structure by creating a new object of type OBJTYPE
% called NEW_OBJNAME
%
% Adds the following objects:
% - object
%
% This function will initialize everything to empty. If you want to
% base your new object on an existing one, use duplicate_object
% instead.
% This looks as though it's very memory-inefficient, but it appears
% that matlab's pretty smart about the way it copies, modifies and passes
% around cell arrays and cells inside them.
%
% If you append a column to a matrix, we think it literally makes a
% copy of the matrix with a larger memory footprint and adds the
% column there. On the other hand, a cell array seems to be just a
% bunch of pointers, so adding cell just means appending a pointer
% without having to make a copy of the contents of the whole cell
% array. There's an ugly demonstration of this in test_mem2, which
% uses the time taken to manipulate very large variables in memory as
% an indication of how much copying is being done.
if nargin~=3
  error('I think you''ve forgotten to feed in all your arguments');
end
if isempty(new_objname)
  error('Can''t create new patterns with empty name');
end
if strcmp(objtype,'subj')
  error('Use init_subj directly. And you can''t store a subj in a subj');
end
if ~isempty(strmatch(new_objname,get_typeslist('single'),'exact'))
  error('It''s a bad idea to name any of your objects of the main types');
end
% Initialize what will become our object
obj.name = new_objname;
obj.header.history = [];
obj.mat = [];
obj.matsize = size([]);
obj.group_name = '';
obj.derived_from = '';
obj.header.description = '';
obj.created.datetime = datetime(true);
% Deal with particular fields that are specific to different types
switch(objtype)
 case 'pattern'
  subj.p = new_objname;
  obj.masked_by = '';
 case 'regressors'
  subj.r = new_objname;
  obj.condnames = [];
 case 'selector'
  subj.s = new_objname;
 case 'mask'
  obj.thresh = NaN;
  obj.nvox = NaN;
  subj.m = new_objname;
end
% In order to work with objects of any type, we're going to get the
% entire cell array for the object and work on that. This way, we
% don't have to refer to subj.patterns or subj.regressors directly
% at all
objcell = get_type(subj,objtype);
nbr_objs = length(objcell);
% Check whether any objs already have this name
for p=1:nbr_objs
  if strcmp(objcell{p}.name,new_objname)
    error( sprintf('One of the %s objects already has this name',objtype) );
  end
end % p nbr_objs
objcell{nbr_objs+1} = obj;
% Now reattach the object to its cell array by overwriting the old
% cell array
subj = set_type(subj,objtype,objcell);