Description of set_object
set_object
PURPOSE
Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
SYNOPSIS
function [subj] = set_object(subj,objtype,objname,obj)
DESCRIPTION
 Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
 [SUBJ] = SET_OBJECT(SUBJ,OBJTYPE,OBJNAME,OBJ)
 For internal use. Use set_mat, set_objfield and set_objsubfield
CROSS-REFERENCE INFORMATION
This function calls:
get_number Internal function - find the cell index of an object
get_type For internal use. Returns the entire cell array of a given type
set_type Replace the entire cell array of this objtype with a new one
This function is called by:
add_history Adds HIST_STR to OBJNAME's history field.
remove_objfield Removes a field from the object
set_objfield Replace or add a field to an object
SOURCE CODE
function [subj] = set_object(subj,objtype,objname,obj)
% Replaces an entire object, i.e. a cell from one of the main 4 cell arrays
%
% [SUBJ] = SET_OBJECT(SUBJ,OBJTYPE,OBJNAME,OBJ)
%
% For internal use. Use set_mat, set_objfield and set_objsubfield
if nargin~=4
  error('I think you''ve forgotten to feed in all your arguments');
end
if ~nargout
  error('Don''t forget to catch the subj structure that gets returned');
end
if ~isstruct(obj)
  error( sprintf('You''re about to overwrite the %s %s with a non-struct', ...
   objname,objtype) );
end
% Get the entire cell array. Mess with the appropriate cell in
% it. Replace the whole cell array
objcell = get_type(subj,objtype);
objno = get_number(subj,objtype,objname);
objcell{objno} = obj;
subj = set_type(subj,objtype,objcell);